[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
	z3t0/IRremote@^4.5.0
	pablomarquez76/PS4_Controller_Host@^1.1.0

build_unflags =
	-std=c++11
	-std=c++14
	-std=gnu++11
	-std=gnu++14

build_flags =
	-O2
	-std=gnu++17
	-Wno-unknown-pragmas
	-Wno-pragmas
	-D_FORTIFY_SOURCE=2
	-D_POSIX_C_SOURCE=202405L

	-D BYTE_SIZE=256
	-D BUFFER_SIZE=512
	-D STACK_SIZE=4096

	-D DEFAULT_KERNEL_STATE=1
	-D PWM_A=23
	-D A_1=18
	-D A_2=19
	-D PWM_B=4
	-D B_1=16
	-D B_2=17
	-D STBY=5
	-D LED=2
	-D IR_TRIGGER=13
	-D SENSOR_TRANSISTOR=25
	-D SENSOR_RIGHT=34
	-D SENSOR_FRONT=36
	-D SENSOR_LEFT=39
	-D RECEIVER_LEFT=5
	-D RECEIVER_FRONT=4
	-D RECEIVER_RIGHT=23

;	-D DEFAULT_KERNEL_STATE=-1
;	-D A_1=16
;	-D A_2=18
;	-D B_1=17
;	-D B_2=16
;	-D LED=2
;	-D IR_TRIGGER=13
;	-D SENSOR_TRANSISTOR=25
;	-D SENSOR_LEFT=36
;	-D SENSOR_FRONT=39
;	-D SENSOR_RIGHT=34
;	-D RECEIVER_LEFT=5
;	-D RECEIVER_FRONT=4
;	-D RECEIVER_RIGHT=23

build_src_flags =
	-Wformat=2
	-Wall
	-Wextra
	-Wvla
	-Wshadow
	-Werror
	-Wno-cpp

monitor_speed = 115200
